### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by amichayoren**

### CODE REVIEW

**Comment by colinhiggs** [comment]
I'm about to review these and try to merge any necessary changes. There has been a fundamental change to the code (the API functionality is now in a class instead of the module) which affected most lines. I will therefore look at the commits one by one and see what needs transferred over.

Colin

**Comment by colinhiggs** [comment]
Hybrid properties I ended up doing before looking at this. Now looking at support for invisible columns. SQLAlchemy docs suggest that the info attribute should be a dictionary rather than a string:

"Info dictionary associated with the object, allowing user-defined data to be associated with this SchemaItem."

Going with the dictionary approach and making a 'pyramid_jsonapi' section for use by this module.

**Comment by colinhiggs** [comment]
Visibility of columns now toggleable via a pyramid_jsonapi member in info dict:

# Add pyramid_jsonapi member to isolate options.
# Note the use of the key 'visible' instead of 'invisible' to avoid thinking in double negatives.
# Note the use of update() so that we don't squash information for other modules or the app.
your_column.info.update({ 'pyramid_jsonapi': { 'visible': True } })

**Comment by colinhiggs** [comment]
Collection renaming now supported via __pyramid_jsonapi__ options dictionary added to models. Use the collection_name member.

**Comment by amichayoren** [comment]
Awesome! Thanks

On Jun 30, 2017, at 2:38 PM, Colin Higgs <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm about to review these and try to merge any necessary changes. There has been a fundamental change to the code (the API functionality is now in a class instead of the module) which affected most lines. I will therefore look at the commits one by one and see what needs transferred over.

Colin

**Comment by colinhiggs** [comment]
Looking at supporting related_patch. There doesn't seem to be anything in the spec which demands support for this, but then there isn't anything that says you shouldn't either - so I don't think supporting this feature breaks the spec.

Meanwhile the method itself probably needs to detect whether the related url points to a collection or not.

**Comment by colinhiggs** [comment]
This branch has diverged too far from master now. I think we've covered most significant changes either as already merged features or as issues.

**Pull request closed without merging**
