### PR TITLE
amichayoren PRs

### PR DESCRIPTION
**Pull request by mrichar1**
PR to add useful bugfixes and features extracted from the diverged PRs.

I've added a message to his PR saying that basically we're going to close them with only a breif glance, but that we'd be keen to know if 2.x will be something he can use (or if it is missing any features).

I've had a scan through his commits and can only see one bug, which I've patched - the rest are either for no-longer-existing code, or make changes that break spec or add features that aren't supoorted.

There are a few commits that might be worth you casting an eye over, since they are adding something that is potentially useful, or dealing with a situation I don't understand:

https://github.com/colinhiggs/pyramid-jsonapi/pull/34/commits/5751ed9bf63e77f9b4a34672b1498c57a7afd06f

This uses a regex with word boundaries instead of a straight replace - I can't think why obj_id would ever have word boundaries, but I might be missing something?

https://github.com/colinhiggs/pyramid-jsonapi/pull/34/commits/7ea161a1663ad522cedda96f944dfefd74bee3a4

This looks like it *might* be a good idea, but I'm not sure if there's actually any reason for this test.

https://github.com/colinhiggs/pyramid-jsonapi/pull/34/commits/fb61cd1fabb7e399c8628492558190a8faffe2f4

Might be useful?

Please consider these, and either push to this branch, or just merge as-is.

### CODE REVIEW

**Comment by colinhiggs** [comment]
> 5751ed9
>
> This uses a regex with word boundaries instead of a straight replace - I can't think why obj_id would ever have word boundaries, but I might be missing something?

That's not manipulating the id: it's manipulating the `primaryjoin` condition, which will be a bit of SQL text. We do it a different way: by filtering on remote column value == object id.

I'm not sure why one would use the text substitution on `primaryjoin`. Perhaps that works on more complicated custom join conditions? It does look a bit fragile though.

**Comment by colinhiggs** [comment]
> 7ea161a
>
> This looks like it might be a good idea, but I'm not sure if there's actually any reason for this test.

This is probably so that foreign key columns appear in the returned data.

`self.requested_field_names` already includes all columns if the `fields` parameter doesn't exist - *except* for foreign key columns, which are currently never returned (they are never added to the list of fields to fetch). This was a design decision: such information should probably come via the relationship.

It is worth considering adding a configuration item to toggle whether foreign keys are excluded in this way or not.

**Comment by mrichar1** [comment]
Thanks for the clarifications! I think last time we discussed 7ea161a we decided to leave this feature until it was needed by someone - this probably is enough evidence that it will be needed! :)

I've just gone over the PRs again, and found a couple more commits of potential interest I missed the first time:

https://github.com/colinhiggs/pyramid-jsonapi/pull/34/commits/92440cfa6af6e0cbc75460dc4f1bcbfcf02c04a7

I can see how this could be useful - it's not explicitly required or forbidden by the spec - any thoughts?

`filter_on_relationships()` - this method is created and patched throughout several commits, which is why I missed it the first time, so it's probably best to look at it in it's finished form at: https://github.com/colinhiggs/pyramid-jsonapi/pull/34/files#diff-7f4eae5e8003c24462bccb61b720f5aeR1811

Again, this is a feature outside the spec, but one that might be useful?

**Comment by colinhiggs** [comment]
Opened issue #125 to potentially take care of 7ea161a

**Comment by colinhiggs** [comment]
Opened issue #128 to add filtering on relationships

**Comment by colinhiggs** [comment]
Opened issue #132 to address d397319

**Comment by colinhiggs** [comment]
That's everything arising from this request either reasoned away or moved into an issue. I'll merge the one bug fix committed and close.

**Pull request merged**
