### PR TITLE
few small enhancments

### PR DESCRIPTION
**Pull request by amichayoren**
Hi,

My name is Amichay, I'm CTO of AppCard (https://www.appcard.com). We've recently started to look into using your package as a way to expose JSON:APIs. I've done couple of small changes and I'd love your comments and suggestions. I haven't had the change to write unit tests, however we've been testing the changes locally. I also noticed there has no been much traffic since last summer and was wondering how is your roadmap like?

Best,
Amichay

### CODE REVIEW

**Comment by colinhiggs** [comment]
Hi Amichay.

Thanks for your interest in pyramid-jsonapi. I would have got back sooner but I've just had my mail server changed and am trying to catch up. I'm also on holiday tomorrow (just for the day) so this message is just a holding message for now. I'll look over the changes properly later this week.

You're right to notice that there hasn't been any development recently: we only use this for a small project at the moment and it meets those needs. However, your email comes just as I'm about to pick up development again so it is quite timely.

**Comment by amichayoren** [comment]
Thank you for getting back to me. We're trying to use the library in a new project we're working on. We thought it will be nice to give back to the community and try to assist in evolving the library. I'm curios to know your roadmap. I could possible add more people to contribute.


Best,

Amichay



________________________________

**Comment by mrichar1** [comment]
Hi,

As you're no doubt aware, your fork of this module is significantly different from the module in master. As such it is no longer viable to attempt to merge these pull requests directly.

We're very close to releasing a 2.x series, at which point we will close these outstanding PRs.  It would be good to know if you might consider switching back to using our project instead of continuing to maintain a release. If there are any issues or missing features which your fork supports which we don't handle, or that you think should be added, please let us know( in new issues and/or PRs).

We will try to have one last review of these outstanding PRs before closing them to see if there are any obvious bugfixes or features we can incorporate, though with code divergence this might not be an easy task! Either way we will close these PRs at the point of a 2.x release.

Thanks!

**Comment by colinhiggs** [comment]
This branch has diverged too far from master now. I think we've covered most significant changes either as already merged features or as issues.

**Pull request closed without merging**
